# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ğº](bold blue)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[ ğº](bold red)'

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
read_only = ' î©µ '
# Disable the package module, hiding it from the prompt completely

[git_metrics]
disabled = false
added_style = 'bold blue'

[git_status]
disabled = true

[cmd_duration] 
min_time = 5000

[sudo]
disabled = false
symbol = 'î¼  '

[jobs]
format = ' [$symbol$number]($style) '

[battery]
format = ' [$symbol$percentage]($style) '

[aws]
symbol = "îŒ½  "
format = 'with [$symbol]($style)'

[buf]
symbol = "ï’ "
format = 'with [$symbol]($style)'

[c]
symbol = "î˜ "
format = 'with [$symbol]($style)'

[conda]
symbol = "ï„Œ "
format = 'with [$symbol]($style)'

[crystal]
symbol = "î˜¯ "
format = 'with [$symbol]($style)'

[dart]
symbol = "î˜ "
format = 'with [$symbol]($style)'

[docker_context]
symbol = "ïŒˆ "
format = 'with [$symbol]($style)'

[elixir]
symbol = "î˜­ "
format = 'with [$symbol]($style)'

[elm]
symbol = "î˜¬ "
format = 'with [$symbol]($style)'

[fennel]
symbol = "îš¯ "
format = 'with [$symbol]($style)'

[fossil_branch]
symbol = "ï˜ "
format = 'with [$symbol]($style)'

[golang]
symbol = "î˜§ "
format = 'with [$symbol]($style)'

[guix_shell]
symbol = "ïŒ¥ "
format = 'with [$symbol]($style)'

[haskell]
symbol = "î· "
format = 'with [$symbol]($style)'

[haxe]
symbol = "î™¦ "
format = 'with [$symbol]($style)'

[hg_branch]
symbol = "ï˜ "
format = 'with [$symbol]($style)'

[hostname]
ssh_symbol = "î¬ "
format = 'with [$symbol]($style)'

[java]
symbol = "î‰– "
format = 'with [$symbol]($style)'

[julia]
symbol = "î˜¤ "
format = 'with [$symbol]($style)'

[kotlin]
symbol = "î˜´ "
format = 'with [$symbol]($style)'

[lua]
symbol = "î˜  "
format = 'with [$symbol]($style)'

[memory_usage]
symbol = "ó°› "
format = 'with [$symbol]($style)'

[meson]
symbol = "ó°”· "
format = 'with [$symbol]($style)'

[nim]
symbol = "ó°†¥ "
format = 'with [$symbol]($style)'

[nix_shell]
symbol = "ïŒ“ "
format = 'with [$symbol]($style)'

[nodejs]
symbol = "îœ˜ "
format = 'with [$symbol]($style)'

[ocaml]
symbol = "î™º "
format = 'with [$symbol]($style)'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "
format = 'with [$symbol]($style)'

[perl]
symbol = "î™¾ "
format = 'with [$symbol]($style)'

[php]
symbol = "î˜ˆ "
format = 'with [$symbol]($style)'

[pijul_channel]
symbol = "ï˜ "
format = 'with [$symbol]($style)'

[python]
symbol = "îˆµ "
format = 'with [$symbol]($style)'

[rlang]
symbol = "ó°Ÿ” "
format = 'with [$symbol]($style)'

[ruby]
symbol = "î‘ "
format = 'with [$symbol]($style)'

[rust]
symbol = "î¨ "
format = 'with [$symbol]($style)'

[scala]
symbol = "îœ· "
format = 'with [$symbol]($style)'

[swift]
symbol = "î• "
format = 'with [$symbol]($style)'

[zig]
symbol = "îš© "
format = 'with [$symbol]($style)'
